name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        image:
          - name: latest
            python_version: "3.11"
          - name: python3.11
            python_version: "3.11"
          - name: python3.10
            python_version: "3.10"
          - name: python3.9
            python_version: "3.9"
          - name: python3.8
            python_version: "3.8"
          - name: python3.7
            python_version: "3.7"
          - name: python3.8-alpine
            python_version: "3.8"
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          context: "{{defaultContext}}:docker-images"
          file: ${{ matrix.image.name }}.dockerfile
          push: true
          tags: lspvic/uwsgi-nginx:${{ matrix.image.name }}